{rule_files: [10000000samples_avg.yml], scrape_configs: [{job_name: fake-exporter,
      scrape_interval: 100ms, static_configs: [{targets: ['localhost:10000', 'localhost:10001',
            'localhost:10002', 'localhost:10003', 'localhost:10004', 'localhost:10005',
            'localhost:10006', 'localhost:10007', 'localhost:10008', 'localhost:10009',
            'localhost:10010', 'localhost:10011', 'localhost:10012', 'localhost:10013',
            'localhost:10014', 'localhost:10015', 'localhost:10016', 'localhost:10017',
            'localhost:10018', 'localhost:10019', 'localhost:10020', 'localhost:10021',
            'localhost:10022', 'localhost:10023', 'localhost:10024', 'localhost:10025',
            'localhost:10026', 'localhost:10027', 'localhost:10028', 'localhost:10029',
            'localhost:10030', 'localhost:10031', 'localhost:10032', 'localhost:10033',
            'localhost:10034', 'localhost:10035', 'localhost:10036', 'localhost:10037',
            'localhost:10038', 'localhost:10039', 'localhost:10040', 'localhost:10041',
            'localhost:10042', 'localhost:10043', 'localhost:10044', 'localhost:10045',
            'localhost:10046', 'localhost:10047', 'localhost:10048', 'localhost:10049',
            'localhost:10050', 'localhost:10051', 'localhost:10052', 'localhost:10053',
            'localhost:10054', 'localhost:10055', 'localhost:10056', 'localhost:10057',
            'localhost:10058', 'localhost:10059', 'localhost:10060', 'localhost:10061',
            'localhost:10062', 'localhost:10063', 'localhost:10064', 'localhost:10065',
            'localhost:10066', 'localhost:10067', 'localhost:10068', 'localhost:10069',
            'localhost:10070', 'localhost:10071', 'localhost:10072', 'localhost:10073',
            'localhost:10074', 'localhost:10075', 'localhost:10076', 'localhost:10077',
            'localhost:10078', 'localhost:10079', 'localhost:10080', 'localhost:10081',
            'localhost:10082', 'localhost:10083', 'localhost:10084', 'localhost:10085',
            'localhost:10086', 'localhost:10087', 'localhost:10088', 'localhost:10089',
            'localhost:10090', 'localhost:10091', 'localhost:10092', 'localhost:10093',
            'localhost:10094', 'localhost:10095', 'localhost:10096', 'localhost:10097',
            'localhost:10098', 'localhost:10099', 'localhost:10100', 'localhost:10101',
            'localhost:10102', 'localhost:10103', 'localhost:10104', 'localhost:10105',
            'localhost:10106', 'localhost:10107', 'localhost:10108', 'localhost:10109',
            'localhost:10110', 'localhost:10111', 'localhost:10112', 'localhost:10113',
            'localhost:10114', 'localhost:10115', 'localhost:10116', 'localhost:10117',
            'localhost:10118', 'localhost:10119', 'localhost:10120', 'localhost:10121',
            'localhost:10122', 'localhost:10123', 'localhost:10124', 'localhost:10125',
            'localhost:10126', 'localhost:10127', 'localhost:10128', 'localhost:10129',
            'localhost:10130', 'localhost:10131', 'localhost:10132', 'localhost:10133',
            'localhost:10134', 'localhost:10135', 'localhost:10136', 'localhost:10137',
            'localhost:10138', 'localhost:10139', 'localhost:10140', 'localhost:10141',
            'localhost:10142', 'localhost:10143', 'localhost:10144', 'localhost:10145',
            'localhost:10146', 'localhost:10147', 'localhost:10148', 'localhost:10149',
            'localhost:10150', 'localhost:10151', 'localhost:10152', 'localhost:10153',
            'localhost:10154', 'localhost:10155', 'localhost:10156', 'localhost:10157',
            'localhost:10158', 'localhost:10159', 'localhost:10160', 'localhost:10161',
            'localhost:10162', 'localhost:10163', 'localhost:10164', 'localhost:10165',
            'localhost:10166', 'localhost:10167', 'localhost:10168', 'localhost:10169',
            'localhost:10170', 'localhost:10171', 'localhost:10172', 'localhost:10173',
            'localhost:10174', 'localhost:10175', 'localhost:10176', 'localhost:10177',
            'localhost:10178', 'localhost:10179', 'localhost:10180', 'localhost:10181',
            'localhost:10182', 'localhost:10183', 'localhost:10184', 'localhost:10185',
            'localhost:10186', 'localhost:10187', 'localhost:10188', 'localhost:10189',
            'localhost:10190', 'localhost:10191', 'localhost:10192', 'localhost:10193',
            'localhost:10194', 'localhost:10195', 'localhost:10196', 'localhost:10197',
            'localhost:10198', 'localhost:10199']}]}]}
