{rule_files: [samples_entropy_concurrent.yml], scrape_configs: [{job_name: fake-exporter,
      scrape_interval: 1ms, static_configs: [{targets: ['localhost:8000', 'localhost:8001',
            'localhost:8002', 'localhost:8003', 'localhost:8004', 'localhost:8005',
            'localhost:8006', 'localhost:8007']}]}]}
