{
  alerting: { alertmanagers: [{ static_configs: [{ targets: null }] }] },
  global: { evaluation_interval: 20s, scrape_interval: 1s },
  rule_files:
    [10samples.yml, 100samples.yml, 1000samples.yml, 10000samples.yml],
  scrape_configs:
    [
      {
        job_name: fake_metric,
        static_configs:
          [{ targets: ["localhost:8000", "localhost:8001", "localhost:8002"] }],
      },
    ],
}
