# my global config
global:
  scrape_interval: 1s # 500ms, 15s default
  evaluation_interval: 1s # 500ms, 15s default
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "prometheus-rules.yml"
  - "promsketch-latency.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
        # The label name is added as a label `label_name=<label_value>` to any timeseries scraped from this config.
        labels:
          app: "prometheus"

  - job_name: 'promsketch'
    static_configs:
      - targets: ['localhost:7000']

  - job_name: "fake_exporter"
    static_configs:
      - targets:
          - "localhost:8000"
          - "localhost:8001"
          - "localhost:8002"
          - "localhost:8003"
          - "localhost:8004"
          - "localhost:8005"
          - "localhost:8006"
          - "localhost:8007"

  # - job_name: "promsketch_raw_groups"
  #   static_configs:
  #     - targets:
  #         - "localhost:7100"
  #         - "localhost:7101"
  #         - "localhost:7102"
  #         - "localhost:7103"
  #         - "localhost:7104"
  #         - "localhost:7105"
  #         - "localhost:7106"
  #         - "localhost:7107"
  #         - "localhost:7108"
  #         - "localhost:7109"
  #         - "localhost:7110"
  #         - "localhost:7111"
  #         - "localhost:7112"
  #         - "localhost:7113"
  #         - "localhost:7114"
  #         - "localhost:7115"
  #         - "localhost:7116"
  #         - "localhost:7117"
  #         - "localhost:7118"
  #         - "localhost:7119"
  #         - "localhost:7120"
  #         - "localhost:7121"
  #         - "localhost:7122"
  #         - "localhost:7123"
  #         - "localhost:7124"
  #         - "localhost:7125"
  #         - "localhost:7126"
  #         - "localhost:7127"
  #         - "localhost:7128"
  #         - "localhost:7129"
  #         - "localhost:7130"
  #         - "localhost:7131"
  #         - "localhost:7132"
  #         - "localhost:7133"
  #         - "localhost:7134"
  #         - "localhost:7135"
  #         - "localhost:7136"
  #         - "localhost:7137"
  #         - "localhost:7138"
  #         - "localhost:7139"
  #         - "localhost:7140"
  #         - "localhost:7141"
  #         - "localhost:7142"
  #         - "localhost:7143"
  #         - "localhost:7144"
  #         - "localhost:7145"
  #         - "localhost:7146"
  #         - "localhost:7147"
  #         - "localhost:7148"
  #         - "localhost:7149"
